adjust for breaking changes in crystal: these return types need to be explicit now
This used to compile before, but then after upgrading Crystal (it was probably
the upgrade to 0.34.0, based on the changelog), I started getting this error:

In src/lox/compiler.cr:58:17

 58 | ParseRule.new(prefix, infix, precedence)
                ^--
Error: no overload matches 'Lox::ParseRule.new' with types (Proc((Array(Int32) | Nil)) | Proc((Bool | Nil)) | Proc(Nil) | Nil), (Proc((Array(Int32) | Nil)) | Proc(Nil) | Nil), Lox::Precedence

Overloads are:
 - Lox::ParseRule.new(prefix : ParseFn | Nil, infix : ParseFn | Nil, precedence : Precedence)
Couldn't find overloads for these types:
 - Lox::ParseRule.new(prefix : Proc((Array(Int32) | Nil)), infix : Proc((Array(Int32) | Nil)), precedence : Lox::Precedence)
 - Lox::ParseRule.new(prefix : Proc((Array(Int32) | Nil)), infix : Proc(Nil), precedence : Lox::Precedence)
 - Lox::ParseRule.new(prefix : Proc((Array(Int32) | Nil)), infix : Nil, precedence : Lox::Precedence)
 - Lox::ParseRule.new(prefix : Proc((Bool | Nil)), infix : Proc((Array(Int32) | Nil)), precedence : Lox::Precedence)
 - Lox::ParseRule.new(prefix : Proc((Bool | Nil)), infix : Proc(Nil), precedence : Lox::Precedence)
 - Lox::ParseRule.new(prefix : Proc((Bool | Nil)), infix : Nil, precedence : Lox::Precedence)
 - Lox::ParseRule.new(prefix : Proc(Nil), infix : Proc((Array(Int32) | Nil)), precedence : Lox::Precedence)
 - Lox::ParseRule.new(prefix : Nil, infix : Proc((Array(Int32) | Nil)), precedence : Lox::Precedence)

 I think it's something to do with a change in Crystal 0.34.0 where the compiler
 will allow you to be looser about the return values of Procs. Like sometimes a
 Proc(Something) can be assignable as a Proc(Nil), or something like that. I
 don't fully understand the change, but it turns out that specifying that these
 methods return Nil fixes the issue because the compiler can be more confident
 about what types are floating around, I guess. ¯\_(ツ)_/¯